#!/bin/bash

read_dom () {
	local IFS=\>
	read -d \( ENTITY CONTENT
}

packfile () {
	libs=`ldd "$2"`
	echo $libs > libs

	mkdir -p $1.app/bin
	mkdir $1.app/libs
	mkdir $1.app/resources

	while read_dom; do
		cp $CONTENT $1.app/libs/
	done < libs

	cp $2 $1.app/bin/
	
	binary_basename=$(basename $2)
	
	interpreter=`readelf -l $1.app/bin/$binary_basename | grep interpreter | grep -oP ": (.*?)]" | head -c -2 | tail -c +3`
	
	interpreter_basename=$(basename $interpreter)
	
	cp $interpreter $1.app/libs/
	
	patchelf --set-interpreter ./libs/$interpreter_basename --set-rpath ./libs/ $1.app/bin/$binary_basename

}

more_deps () {

	package="$1"

	further=0

	while true; do
		read -p "Are there any more EXECUTABLE dependencies? (y/n) " yn
		case $yn in
			[Yy]* ) further=1; break;;
			[Nn]* ) exit 0; break;;
			* ) echo "Answer yes or no";;
		esac
	done
	
	if [[ further -eq 1 ]]; then
		while true; do
			read -p "Please specify the full path of the executable dependency: " depbinary
			case $depbinary in
				* ) break;;
			esac
		done
		
		packfile $package $depbinary
	fi
	
	more_deps $1
}

primary_binary_name=$(basename $1)

packfile $primary_binary_name $1

echo "<app>" > $primary_binary_name.app/appinfo
echo "	<name>$primary_binary_name</name>" >> $primary_binary_name.app/appinfo
echo "	<main>bin/$primary_binary_name</main>" >> $primary_binary_name.app/appinfo
echo "</app>" >> $primary_binary_name.app/appinfo

more_deps $1
